# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# Cada termino nuevo en la secuencia de Fibonacci es generado añadiendo los dos terminos anteriores. Los primeros 10 terminos serian:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# Considerando que los terminos en la secuencia de fibonacci no exedan los cuatro millones, encuentra la suma de los terminos evaluados.

d = []
r = 1
n = 1
while True:
    r = r + n
    n = n + r
    d.append(n)
    d.append(r)